language: cpp
sudo: enabled
dist: trusty
env:
  matrix:
  - CONF=Debug   COMPILER=g++-6   COVERAGE=0
  - CONF=Release COMPILER=g++-6   COVERAGE=0
before_install:
- sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository --yes ppa:libreoffice/ppa
- sudo add-apt-repository --yes ppa:andykimpe/cmake3
- sudo apt-get update
install:
- sudo apt-get install --yes --force-yes cmake3 g++-6 libgtest-dev;
script:
- "${COMPILER} --version"
- cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${CONF} -DCOVERAGE=${COVERAGE}
- make VERBOSE=1
- make test
