language: cpp
env:
  matrix:
  - CONF=Debug   COMPILER=g++-6   COVERAGE=0
  - CONF=Release COMPILER=g++-6   COVERAGE=0
before_install:
- sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository --yes ppa:libreoffice/ppa
- sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x
- sudo apt-get update
install:
- sudo apt-get install --yes --force-yes cmake g++-6;
script:
- "${COMPILER} --version"
- cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${CONF} -DCOVERAGE=${COVERAGE}
- make VERBOSE=1
- make test
